remote_theme: qwtel/hydejack@gem-7.4.2
accent_color: '#6a9fb5'
accent_image: none
title: Austin Huang
description: Chatbot developer / High school student / Montréal, QC
plugins:
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
url: https://austinhuang.me
lang: en
author:
  name:                Austin Huang
  email:               im@austinhuang.me
  twitter:             montreal0131
