title: Austin Huang
description: Chatbot developer / High school student / Montréal, QC
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
url:                   https://austinhuang.me
lang:                  en
tagline:               A JavaScript developer than makes chatbots with love in Canada.
keywords:              []
author:
  name:                Austin Huang
  email:               im@austinhuang.me
  twitter:             montreal0131
copyright:             © 2017. All rights reserved.
permalink:             pretty

remote_theme: nandomoreirame/lora
