remote_theme: qwtel/hydejack

title: Austin Huang
tagline: WIP new site...

accent_color: '#87CEFA'
accent_image:
  background: '#bada55'

author:
  name:  Austin Huang
  email: im@austinhuang.me

  social:
    email: mailto:im@austinhuang.me
    github: austinhuang0131
    instagram: austinhuang0131
    twitter: montreal0131
    telegram: austinhuang

exclude:
  - Makefile
