remote_theme: qwtel/hydejack

title: Austin Huang
tagline: A young JavaScript developer who writes chatbots and stories in Montreal.

accent_color: '#87CEFA'
accent_image:
  background: '#bada55'
  
disqus: '0131'

url: https://austinhuang.me

author:
  name:  Austin Huang
  email: im@austinhuang.me
  social:
    email: mailto:im@austinhuang.me
    github: austinhuang0131
    flickr: austin0131
    tumblr: austinhuang0131
    paypal: discordtel
    telegram: austinhuang
    instagram: austinhuang0131
    twitter: montreal0131
    reddit: austinhuang
    steam: austinhuang0131

plugins:
  - jekyll-avatar

include:
  - assets
exclude:
  - Makefile
